name: CI Pipeline

on:
  push:
    branches:
      - precompilation
    # paths:
    #   - 'gbrl/**'   # Trigger on changes to files in the src directory
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov g++ gcc

    - name: Install dependencies on MacOs
      if: matrix.os == 'macos-latest'
      run: |
        brew install libomp llvm
        # Dynamic paths for Homebrew-installed tools

    - name: Install Python dependencies and build the project with coverage
      run: |
        python -m pip install --upgrade pip
        BREW_PREFIX=$(brew --prefix)

        # Environment variables for LLVM and other tools
        export LDFLAGS="-L$(brew --prefix ffmpeg)/lib -L$(brew --prefix libomp)/lib -L$(brew --prefix llvm)/lib -L$(brew --prefix llvm)/
        lib/c++ -Wl,-rpath,$(brew --prefix llvm)/lib/c++"
        export CPPFLAGS="-I$(brew --prefix ffmpeg)/include -I$(brew --prefix libomp)/include -I$(brew --prefix llvm)/include"
        export CC="$(brew --prefix llvm)/bin/clang"
        export CXX="$(brew --prefix llvm)/bin/clang++"
        #export CXX="/usr/bin/g++"
        #export C="/usr/bin/gcc"
        # Ensure LLVM bin is in PATH
        export PATH="$(brew --prefix llvm)/bin:$PATH"
        export DYLD_LIBRARY_PATH=/opt/homebrew/opt/llvm/lib:/opt/homebrew/opt/libomp/lib
        export CMAKE_PREFIX_PATH=$(brew --prefix llvm)
        pip install .

    - name: Run tests
      run: |
        python -m unittest discover tests


